language: node_js
node_js:
- lts/*
- node
install: yarn
script:
- yarn prettify
- 
- yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: yanishproduction@gmail.com
  api_key:
    secure: JaWxdBtA4xl6tyZQcP448lJvaGng3Xz4BWyeUaiHotjSI69XdGZLeGbYU3as7Zi3let2qtdDAChLc5AhfTtrgO21P2f2c6c/ncPprb+xb5IwQBdZn4hKXb5cBKBwjqsuH1Jp4DkEjcJuliJve0xyoqCD2oE3qXIVrmBbNYd9EuISHZVMUd+ZDnZ/HMmWTekErFlyoFnpg6Po2yMYEKq8mATPLvDM3lkq1fnNYSEK26I4csToO4apdUilFJzuWLV/2KnAnEnOfZe7ksIm/a9Rkl2h6u35p5fKno9WATbrBw6Gd2fO1I8Fku4/4S26QhnaKHGOF2iqZVghT/WiQZFSPAK13uBZAkLreKDYkQVcwA4AaxteypfNvg03b27j5quQyCWITwvqpxFLm0G/dL68irjJA8il756kQIF1YULSdNMSDFXIXtkzvAWl5GDt8elWyJoQvsfQO4K/+H3yNjnP2bm0vamXbfxJ2+epWJj9wtoJ6GZtS55kpqZciFQc3gIbutAht1R/Rol8rw/8CYyLFh+uKHGttepcIFmZrwv161dA4NGaePreZS4tKV7YUgnRMa46VdVJPUdZ87iXPYZYIYABRX0E4oogSHN+S79B226xabQ7W8F6yYyKUdlWeebWsnk91tiGsz7v2l3Nx8WfEnTS1sPpCptbaK+8/5E978M=
  on:
    tags: true
    branch: master
